# Clinsig words to keep
clin_sig_words: ['pathogenic']


vep_fields: ['Consequence','Gene','HGVSc','HGVSp','SYMBOL','Existing_variation','gnomADg_AF_POPMAX','gnomADe_AF_POPMAX','PICK','CLIN_SIG', 'EXON', 'INTRON', 'Feature','SIFT','PolyPhen','ccrs','SpliceAI_DS_AG','SpliceAI_DS_AL','SpliceAI_DS_DG','SpliceAI_DS_DL','SpliceAI_SYMBOL']


to_keep_consequences:
               'transcript_ablation': 'transcript_ablation'
               'splice_acceptor_variant': 'splice_acceptor_variant'
               'splice_donor_variant': 'splice_donor_variant'
               'stop_gained': 'stop_gained'
               'frameshift_variant': 'frameshift_variant'
               'stop_lost': 'stop_lost'
               'start_lost': 'start_lost'
               'transcript_amplification': 'transcript_amplification'
               'inframe_insertion': 'inframe_insertion'
               'inframe_deletion': 'inframe_deletion'
               'missense_variant': 'missense_variant'
               'protein_altering_variant': 'protein_altering_variant'
               'splice_region_variant': 'splice_region_variant'
               'incomplete_terminal_codon_variant': 'incomplete_terminal_codon_variant'
               'start_retained_variant': 'start_retained_variant'
               'stop_retained_variant': 'stop_retained_variant'
               


consequence_severity: ['transcript_ablation','splice_acceptor_variant','splice_donor_variant','stop_gained','frameshift_variant','stop_lost','start_lost','transcript_amplification','inframe_insertion','inframe_deletion','missense_variant','protein_altering_variant','splice_region_variant','incomplete_terminal_codon_variant','start_retained_variant','stop_retained_variant','synonymous_variant','coding_sequence_variant','mature_miRNA_variant','5_prime_UTR_variant','3_prime_UTR_variant','non_coding_transcript_exon_variant','intron_variant','NMD_transcript_variant','non_coding_transcript_variant','upstream_gene_variant','downstream_gene_variant','TFBS_ablation','TFBS_amplification','TF_binding_site_variant','regulatory_region_ablation','regulatory_region_amplification','feature_elongation','regulatory_region_variant','feature_truncation','intergenic_variant']


hpo_file: 'ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt'


gnomad_gene_scores: '/Users/josephhalstead/Documents/genomics_resources/annotations/release_2.1_ht_constraint_constraint_refseq.txt'

#Per sample quality cutoffs

min_dp: 10
min_gq: 20



default_cutoff_gnomad_genomes: 0.01
default_cutoff_gnomad_exomes: 0.01
splice_ai_cutoff: 0.2


min_parental_depth_dn: 10
min_parental_gq_dn: 20
min_parental_depth_uid: 10
min_parental_gq_uid: 20

# Time in days if data in local panel app dump older than this then query API
panel_app_dump_max_time: 100.0

# Cutoffs for the different workflows
other_gnomadg: 0.01
other_gnomade: 0.01

comp_het_gnomadg: 0.01
comp_het_gnomade: 0.01

upi_gnomadg: 0.01
upi_gnomade: 0.01

rec_sex_gnomadg: 0.01
rec_sex_gnomade: 0.01
rec_sex_ac: 8

rec_auto_gnomadg: 0.01
rec_auto_gnomade: 0.01
rec_auto_ac: 4

dom_sex_gnomadg: 0.0075
dom_sex_gnomade: 0.001
dom_sex_ac: 6

dom_auto_gnomadg: 0.0075
dom_auto_gnomade: 0.001
dom_auto_ac: 4

de_novo_gnomadg: 0.0075
de_novo_gnomade: 0.001
de_novo_ac: 4
